### ISSUE TITLE
fix errors when dacast content is deleted

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/xiome#67]
how to make the error happen
1. link a dacast account
2. set a xiome-video-display to a piece of dacast content
3. delete the content in the dacast backoffice
4. refresh the page with the xiome-video-display and see that the server is throwing an error

**Comment by chase-moskal** [comment]
```
[2021-10-21::02:36:43.781] 🚨 unexpected error!
 TypeError: Cannot read property 'pictures' of null
    at ingestDacastContent (file:///work/xiome/x/features/videos/api/services/routines/ingest-dacast-content.js:2:28)
    at file:///work/xiome/x/features/videos/api/services/content-service.js:93:28
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Promise.all (index 0)
    at async execute (file:///work/xiome/node_modules/renraku/x/servelet/make-servelet.js:23:28)
    at async file:///work/xiome/node_modules/renraku/x/server/make-request-listener.js:6:33
    at async Server.<anonymous> (file:///work/xiome/node_modules/renraku/x/server/node/allow-cors.js:11:13)
```
